# This file defines the classification categories used by ClassifAI.
# The application will use this list to classify documents.

- Analyses
- Archives
- Audio
- Budgets
- Clés et Certificats
- Contrats
- CV
- Divers
- Documents Multimédia
- Factures
- Fichiers de Code
- Fichiers de Configuration
- Fichiers E-mail
- Fichiers Spécifiques
- Fichiers Texte
- Fichiers Web
- Images
- Justificatifs
- Lettres
- Listes
- Manuels
- Non Classé
- Ordonnances
- Présentations
- Rapports
- Relevés Bancaires
- Sauvegardes
- Scripts
- Tableaux
- Tickets
- Vidéos
